version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_orders
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - backend_network


  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - backend_network


  logstash:
    image: logstash:8.12.0
    volumes:
      - ./app/deploy/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "12201:12201"
    depends_on:
      - elasticsearch
    networks:
      - backend_network


  kibana:
    image: kibana:8.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - backend_network


  fastapi_orders_service:
    build: .
    volumes:
      - .:/app
    container_name: fastapi_auth_service
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - db
      - logstash
    networks:
      - backend_network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./app/deploy/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./app/deploy/grafana_datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  es_data: